name: Docker Image Producer CI

on:
  push:
    branches:
      - 'lab1'
    #paths:
    #  - 'producer'
    # pull_request:
    #  branches: lab1
    #paths:
    #  - 'procuder/producer.py'

jobs:
  editorconfig:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: EditorConfig Check
        run: |
          npx editorconfig-checker

  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Super-Linter
        uses: super-linter/super-linter@v5.6.1

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [ editorconfig,linter ]

    steps:
      - name: AzureLogin
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: AzureContainerRegistryLogin
        run: az acr login --name fervjestinaregistry.azurecr.io

      - name: DockerImageBuild
        run: docker build -t fervjestinaregistry.azurecr.io/producer:latest producer

      - name: PushDockerImageToACR
        run: docker push fervjestinaregistry.azurecr.io/producer:latest

      - name: DeployAzureContainerApps
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: fervjestina
          containerAppName: producer
          image: fervjestinaregistry.azurecr.io/producer:latest
          namespace: default

